import type { ChemicalSupply } from "./types";

/**
 * Initial data store of the application
 * */
export const initialChemicalSupplies: Array<ChemicalSupply> = [
  {
    id: 1,
    chemicalName: "Ammonium Persulfate",
    vendor: "LG Chem",
    density: 3525.92,
    viscosity: 60.63,
    packaging: "Bag",
    packSize: 100.0,
    unit: "kg",
    quantity: 6495.18,
  },
  {
    id: 2,
    chemicalName: "Caustic Potash",
    vendor: "Formosa",
    density: 3172.15,
    viscosity: 48.22,
    packaging: "Bag",
    packSize: 100.0,
    unit: "kg",
    quantity: 8751.9,
  },
  {
    id: 3,
    chemicalName: "Dimethylaminopropylamino",
    vendor: "LG Chem",
    density: 8435.37,
    viscosity: 12.62,
    packaging: "Barrel",
    packSize: 75.0,
    unit: "L",
    quantity: 5964.61,
  },
  {
    id: 4,
    chemicalName: "Mono Ammonium Phosphate",
    vendor: "Sinopec",
    density: 1597.65,
    viscosity: 76.51,
    packaging: "Bag",
    packSize: 105.0,
    unit: "kg",
    quantity: 8183.73,
  },
  {
    id: 5,
    chemicalName: "Ferric Nitrate",
    vendor: "DowDuPont",
    density: 364.04,
    viscosity: 14.9,
    packaging: "Bag",
    packSize: 105.0,
    unit: "kg",
    quantity: 4154.33,
  },
  {
    id: 6,
    chemicalName: "n-Pentane",
    vendor: "Sinopec",
    density: 4535.26,
    viscosity: 66.76,
    packaging: "Barrel",
    packSize: 200.0,
    unit: "L",
    quantity: 6272.34,
  },
  {
    id: 7,
    chemicalName: "Glycol Ether PM",
    vendor: "LG Chem",
    density: 6495.18,
    viscosity: 72.12,
    packaging: "Bag",
    packSize: 250.0,
    unit: "kg",
    quantity: 8749.54,
  },
  {
    id: 8,
    chemicalName: "Sodium Hydroxide",
    vendor: "BASF",
    density: 2130.0,
    viscosity: 55.3,
    packaging: "Drum",
    packSize: 50.0,
    unit: "kg",
    quantity: 3000.0,
  },
  {
    id: 9,
    chemicalName: "Hydrochloric Acid",
    vendor: "Evonik",
    density: 1190.0,
    viscosity: 1.9,
    packaging: "Tank",
    packSize: 1000.0,
    unit: "L",
    quantity: 5500.0,
  },
  {
    id: 10,
    chemicalName: "Ethylene Glycol",
    vendor: "Shell",
    density: 1113.0,
    viscosity: 16.1,
    packaging: "IBC",
    packSize: 1000.0,
    unit: "L",
    quantity: 4200.0,
  },
  {
    id: 11,
    chemicalName: "Acetone",
    vendor: "ExxonMobil",
    density: 784.0,
    viscosity: 0.32,
    packaging: "Drum",
    packSize: 200.0,
    unit: "L",
    quantity: 2800.0,
  },
  {
    id: 12,
    chemicalName: "Methanol",
    vendor: "Methanex",
    density: 792.0,
    viscosity: 0.59,
    packaging: "Tank",
    packSize: 5000.0,
    unit: "L",
    quantity: 15000.0,
  },
  {
    id: 13,
    chemicalName: "Sulfuric Acid",
    vendor: "Chemours",
    density: 1840.0,
    viscosity: 26.7,
    packaging: "Tank",
    packSize: 2000.0,
    unit: "L",
    quantity: 10000.0,
  },
  {
    id: 14,
    chemicalName: "Toluene",
    vendor: "Total",
    density: 867.0,
    viscosity: 0.59,
    packaging: "Drum",
    packSize: 200.0,
    unit: "L",
    quantity: 3600.0,
  },
  {
    id: 15,
    chemicalName: "Isopropyl Alcohol",
    vendor: "Dow",
    density: 786.0,
    viscosity: 2.04,
    packaging: "IBC",
    packSize: 1000.0,
    unit: "L",
    quantity: 5800.0,
  },
];
